### ISSUE TITLE
Type of lat and lng for points is string

### ISSUE THREAD

**Issue by MetalMatze** [phaza/laravel-postgis#8]
Hi, 

I just found out, that when using `Point::fromWKT('POINT(1 2)');` the type of lat and lng is string.
That's bad, right?

I saw that in the [PointTest](https://github.com/phaza/laravel-postgis/blob/065cb6963cb42ad533d3804852f02a6de73c25dc/tests/Geometries/PointTest.php#L13) there's `assertEquals()` in used. This should be changed to `assertSame()` to use type checking.

We could prevent this by casting all *Point* inputs to `float`.
That way a point would always consist of floats, which is also the type that PostGIS uses to store.
http://postgis.net/docs/ST_Point.html
Then it will always return `floats` even it something like `0.0` or `2.0`, but I think that's not bad. Having `float ` type is way more important.

I'm going to create a pull request for this, alright?

**Comment by phaza** [comment]
It doesn't really matter, since the values are cast to string when we send them to postgres anyway:
https://github.com/phaza/laravel-postgis/blob/master/src/Eloquent/Builder.php#L27
https://github.com/phaza/laravel-postgis/blob/master/src/Eloquent/PostgisTrait.php#L25

However I think it's nice to be specific about floats in the PHP code, so I think we should do this,
